2019-07-30 14:58:14,330 - GlobalLogs - INFO - Started..
2019-07-30 14:58:14,351 - GlobalLogs.NetEmbs.DataProcessing.prepare_data - INFO - Original shape of DataFrame is (100, 4)
2019-07-30 14:58:14,353 - GlobalLogs.NetEmbs.DataProcessing.prepare_data - INFO - Deleted all NaNs and Strings values from 'Value' column: (100, 4)
2019-07-30 14:58:14,360 - GlobalLogs.NetEmbs.DataProcessing.prepare_data - INFO - After merging FAs the shape is: (100, 6)
2019-07-30 14:58:14,370 - GlobalLogs.NetEmbs.DataProcessing.prepare_data - INFO - After normalization the shape is: (76, 7)
2019-07-30 14:58:14,405 - GlobalLogs.NetEmbs.DataProcessing.prepare_data - INFO - Final shape of DataFrame is: (76, 9)
2019-07-30 14:58:14,419 - GlobalLogs.FSN.utils - INFO - Current SAMPLING parameters: 
 WindowSize:  2 
 Pressure:  20
 Strategy:  MetaDiff
2019-07-30 14:58:15,034 - GlobalLogs.SkipGram - INFO - Current TensorFlow parameters: 
 Embedding size:  8 
 Steps:  50000
 Batch size:  256
2019-07-30 14:58:15,444 - GlobalLogs - ERROR - We've got an error in get_embs_TF function... 
Traceback (most recent call last):
  File "/Users/lex/Dev/GitHub/NetEmbs/model/MakeItGreate.py", line 86, in <module>
    embeddings, run_times = get_embs_TF(evaluate_time=True)
  File "/Users/lex/Dev/GitHub/NetEmbs/NetEmbs/SkipGram/tensor_flow.py", line 168, in get_embs_TF
    CONFIG.WORK_FOLDER[0] + CONFIG.WORK_FOLDER[1] + CONFIG.WORK_FOLDER[2] + '/train', graph)
  File "/anaconda3/envs/DL/lib/python3.7/site-packages/tensorflow/python/summary/writer/writer.py", line 367, in __init__
    filename_suffix)
  File "/anaconda3/envs/DL/lib/python3.7/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "/anaconda3/envs/DL/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/anaconda3/envs/DL/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /train; Permission denied
